apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: todo-frontend
    release: {{ .Release.Name }}
